# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json

# This config only overrides prettier defaults.
semi: false
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
arrowParens: avoid
