# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json

# This config only overrides prettier defaults.
semi: false
plugins:
  - prettier-plugin-organize-imports
arrowParens: avoid