name: "Build"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Build Chromium
        run: pnpm build --zip --tag=dev
      - name: Build Firefox
        run: pnpm build --zip --tag=dev --target=firefox-mv2
      - name: Upload Chromium Extension
        uses: actions/upload-artifact@v4
        with:
          name: chromium-extension
          path: build/chrome-mv3-dev.zip
      - name: Upload Firefox Extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: build/firefox-mv2-dev.zip

        # - name: Browser Platform Publish
      #   uses: PlasmoHQ/bpp@v3
      #   with:
      #     keys: ${{ secrets.SUBMIT_KEYS }}
      #     artifact: build/chrome-mv3-prod.zip
