name: "Build"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build Chromium
        run: pnpm build --zip --tag=dev
      - name: Build Firefox
        run: pnpm build --zip --tag=dev --target=firefox-mv2
      - name: Upload Chromium Extension
        uses: actions/upload-artifact@v4
        with:
          name: chromium-extension
          path: build/chrome-mv3-dev.zip
      - name: Upload Firefox Extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: build/firefox-mv2-dev.zip

        # - name: Browser Platform Publish
      #   uses: PlasmoHQ/bpp@v3
      #   with:
      #     keys: ${{ secrets.SUBMIT_KEYS }}
      #     artifact: build/chrome-mv3-prod.zip
